### ISSUE TITLE
Warning message: In i.p(...) :   installation of package ‘C:/Users/ASUS/AppData/Local/Temp/RtmpsBUL5x/file329c73692beb/fastplm_1.0.8.tar.gz’ had non-zero exit status

### ISSUE THREAD

**Issue by h1019753743** [xuyiqing/fastplm#16]
Dear Xu:
       I ran into this problem when I installed the fastplm package, and I don’t know how to solve it.
       Warning message: In i.p(...) :   installation of package ‘C:/Users/ASUS/AppData/Local/Temp/RtmpsBUL5x/file329c73692beb/fastplm_1.0.8.tar.gz’ had non-zero exit status
       Do you encounter the same problem during installation? Looking forward to your answer

**Comment by h1019753743** [comment]
One more thing: I installed it on windows

**Comment by xuyiqing** [comment]
Ziyi, could you help? Is this up to date?

**Comment by lzy318** [comment]
> One more thing: I installed it on windows

I can successfully install it on my windows device, are you using the latest Rtools to install this package?

**Comment by h1019753743** [comment]
> > One more thing: I installed it on windows
> 
> I can successfully install it on my windows device, are you using the latest Rtools to install this package?

Yes, I installed Rtools, and I can successfully install Mr. Xu’s "gsynth" package.

**Comment by lzy318** [comment]
Thanks. Could you show me the error message in the installation? You can directly send it to zyliu2020@uchicago.edu.

**Comment by h1019753743** [comment]
> > > One more thing: I installed it on windows
> > 
> > 
> > I can successfully install it on my windows device, are you using the latest Rtools to install this package?
> 
> Yes, I installed Rtools, and I can successfully install Mr. Xu’s "gsynth" package.



> Thanks. Could you show me the error message in the installation? You can directly send it to [zyliu2020@uchicago.edu](mailto:zyliu2020@uchicago.edu).

I use another win10 computer, and I didn’t find this problem
